# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  back:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "back/package.json" }}
      - run:
          name: install dependecies for back-end
          command: cd back && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "back/package.json" }}
          paths:
            - ./back/node_modules
      - run:
          name: run tests for back-end
          command: cd back && npm test

  front:
    # specify the version you desire here
    - image: circleci/node:7.10

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

  working_directory: ~/repo

  steps:
    - checkout

    - restore_cache:
        key: dependency-cache-{{ checksum "front/package.json" }}
    - run:
        name: install dependecies for front-end
        command: cd front && npm install
    - save_cache:
        key: dependency-cache-{{ checksum "front/package.json" }}
        paths:
          - ./front/node_modules
    - run:
        name: run tests for front-end
        command: cd front && npm test

workflows:
  version: 2
  back_and_front:
    jobs:
      - back
      - front
